wip1
GameFeeder/GameFeeder pull request #247
Opened 2020-05-14 22:26 UTC by zachkont

![image](https://user-images.githubusercontent.com/17274058/81991953-18bd6380-964b-11ea-9360-57fbf9da841e.png)

2020-09-03 18:59 UTC, TimJentzsch requested changes

2020-09-03 18:59 UTC, TimJentzsch commented on tests/game.spec.ts
> +  let testGame: Game;
Is the eslint disable still needed?

2020-09-03 18:59 UTC, TimJentzsch commented on tests/user.spec.ts
> +  beforeAll(() => {
Is the eslint disable still needed?

2020-09-03 18:59 UTC, TimJentzsch commented on tests/channel.spec.ts
> +  beforeAll(() => {
Is this intentionally skipped?

2020-09-04 16:19 UTC, zachkont commented on tests/channel.spec.ts
> +  beforeAll(() => {
yeah, needs more work

2020-09-04 16:25 UTC, TimJentzsch approved these changes

2020-09-04 16:26 UTC, merged